translation: ANL UE

ANL:
	wmlxgettext --recursive --directory=.. --domain=wesnoth-ANLEra -o wesnoth-ANLEra.pot
	msgmerge -U de/LC_MESSAGES/wesnoth-ANLEra.po wesnoth-ANLEra.pot
	msgfmt -o de/LC_MESSAGES/wesnoth-ANLEra.mo de/LC_MESSAGES/wesnoth-ANLEra.po

UE:
	wmlxgettext --recursive --directory=.. --domain=wesnoth-Undead_Empire -o wesnoth-Undead_Empire.pot
	msgmerge -U de/LC_MESSAGES/wesnoth-Undead_Empire.po wesnoth-Undead_Empire.pot
	msgfmt -o de/LC_MESSAGES/wesnoth-Undead_Empire.mo de/LC_MESSAGES/wesnoth-Undead_Empire.po
