translation:
	wmlxgettext --recursive --directory=.. --domain=wesnoth-ANLEra -o wesnoth-ANLEra.pot
	msgmerge -U de/wesnoth-ANLEra.po wesnoth-ANLEra.pot
	msgfmt -o de/LC_MESSAGES/wesnoth-ANLEra.mo de/wesnoth-ANLEra.po
